import "server-only";

import nodemailer from "nodemailer";
import {
  getSmtpAppPassword,
  getSmtpFromAddress,
  getSmtpHost,
  getSmtpPort,
  getSmtpSecure,
  getSmtpUser,
} from "@/lib/env";

/**
 * Email module for outbound technical-report delivery — Phase 10b.
 *
 * Phase 10 originally used Resend with a custom verified domain. Phase
 * 10b swaps that for Gmail SMTP via nodemailer + a Google App Password
 * because the project does not own a custom domain. The exported
 * `sendReportEmail(input) → { providerMessageId }` contract is the same
 * as the Resend version, so the send / resend route handlers consume
 * this module unchanged.
 *
 * Server-only: this file is imported only from API route handlers (the
 * `import "server-only"` directive at the top makes any client-component
 * import a build-time error).
 *
 * Routes that consume this module MUST set
 *   export const runtime = "nodejs";
 * nodemailer is Node-targeted.
 *
 * Out of scope here:
 *   - notification_logs INSERT/UPDATE (Step 8 of Phase 10 — owned by
 *     the API route, not this module)
 *   - calling fn_send_and_complete_report
 *   - storage upload + signed URL minting
 *   - retry / rate-limit logic
 *
 * Why a per-call factory (no module-level singleton):
 *   nodemailer transporters hold an SMTP connection plus credentials.
 *   In a serverless runtime, module-level singletons can outlive a
 *   request and leak credentials / sockets across invocations. Building
 *   a fresh transporter is cheap and guarantees no cross-request leaks.
 *
 * No connection pooling: passing `pool: true` to nodemailer would keep
 * SMTP connections alive between sends, which only matters in long-
 * lived Node processes — not on Vercel's per-invocation runtime.
 */

export type SendReportEmailInput = {
  /** Recipient email address (validated upstream — typically
   *  appointment_requests.email). */
  to: string;
  /** Recipient display name (typically appointment.full_name).
   *  Pass null when missing; the email falls back to a neutral greeting. */
  customerName: string | null;
  /** Vehicle plate associated with the report. Used in the subject line. */
  carPlate: string;
  /** Short report identifier for human reference (e.g., first 8 chars of
   *  the report UUID). Used in the subject line and body. */
  reportShortId: string;
  /** PDF bytes generated by `generateReportPdf` from the PDF module. */
  pdfBuffer: Buffer;
  /** Filename surfaced to the recipient when they download the attachment.
   *  Should end in `.pdf`. */
  pdfFilename: string;
};

export type SendReportEmailResult = {
  /** The SMTP Message-Id header set by Gmail (e.g.,
   *  `<…@…gmail.com>`). Persist in
   *  notification_logs.provider_message_id by the API route. */
  providerMessageId: string;
};

function createTransporter(): nodemailer.Transporter {
  return nodemailer.createTransport({
    host: getSmtpHost(),
    port: getSmtpPort(),
    secure: getSmtpSecure(),
    auth: {
      user: getSmtpUser(),
      pass: getSmtpAppPassword(),
    },
  });
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildSubject(carPlate: string, reportShortId: string): string {
  return `Informe técnico AUTOMATISA · Placa ${carPlate} · N.° ${reportShortId}`;
}

function buildHtml({
  customerName,
  carPlate,
  reportShortId,
}: {
  customerName: string | null;
  carPlate: string;
  reportShortId: string;
}): string {
  const safeName = customerName?.trim()
    ? escapeHtml(customerName.trim())
    : null;
  const greeting = safeName ? `Hola ${safeName},` : "Hola,";
  const safePlate = escapeHtml(carPlate);
  const safeReportId = escapeHtml(reportShortId);

  return [
    `<!DOCTYPE html>`,
    `<html lang="es">`,
    `<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; color: #031633; line-height: 1.5; max-width: 560px; margin: 0 auto; padding: 24px;">`,
    `  <p style="font-size: 16px; margin: 0 0 16px;">${greeting}</p>`,
    `  <p style="margin: 0 0 16px;">Adjuntamos el informe técnico del servicio realizado al vehículo con placa <strong>${safePlate}</strong>.</p>`,
    `  <p style="margin: 0 0 16px;">Encontrarás el documento en formato PDF al final de este correo (referencia interna N.° ${safeReportId}).</p>`,
    `  <p style="margin: 0 0 16px;">Si tienes consultas sobre el informe, responde a este correo o escríbenos por WhatsApp.</p>`,
    `  <p style="margin: 24px 0 4px; font-weight: 600;">AUTOMATISA</p>`,
    `  <p style="margin: 0; color: #475569; font-size: 14px;">Servicio técnico automotriz</p>`,
    `</body>`,
    `</html>`,
  ].join("\n");
}

function buildText({
  customerName,
  carPlate,
  reportShortId,
}: {
  customerName: string | null;
  carPlate: string;
  reportShortId: string;
}): string {
  const greeting = customerName?.trim()
    ? `Hola ${customerName.trim()},`
    : "Hola,";
  return [
    greeting,
    "",
    `Adjuntamos el informe técnico del servicio realizado al vehículo con placa ${carPlate}.`,
    `Encontrarás el documento en formato PDF al final de este correo (referencia interna N.° ${reportShortId}).`,
    "",
    "Si tienes consultas sobre el informe, responde a este correo o escríbenos por WhatsApp.",
    "",
    "AUTOMATISA",
    "Servicio técnico automotriz",
  ].join("\n");
}

/**
 * Sends the technical report email with the PDF attached via Gmail SMTP.
 *
 * Throws on any provider error; the route's existing try/catch records
 * the failure in notification_logs (status='failed', error_message
 * captured). The thrown message is wrapped in `"SMTP send failed: …"`
 * so the route's diagnostic log distinguishes provider errors from
 * upstream issues.
 */
export async function sendReportEmail(
  input: SendReportEmailInput
): Promise<SendReportEmailResult> {
  const { to, customerName, carPlate, reportShortId, pdfBuffer, pdfFilename } =
    input;

  const transporter = createTransporter();

  let info: Awaited<ReturnType<typeof transporter.sendMail>>;
  try {
    info = await transporter.sendMail({
      from: getSmtpFromAddress(),
      to,
      subject: buildSubject(carPlate, reportShortId),
      html: buildHtml({ customerName, carPlate, reportShortId }),
      text: buildText({ customerName, carPlate, reportShortId }),
      attachments: [
        {
          filename: pdfFilename,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "unknown error";
    throw new Error(`SMTP send failed: ${message}`);
  }

  if (!info.messageId) {
    throw new Error("SMTP send succeeded but returned no message id");
  }

  return { providerMessageId: info.messageId };
}
